version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: voltairefrench
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: amir
      POSTGRES_PASSWORD: amir1381
      POSTGRES_DB: voltairefrench
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: